### ISSUE TITLE
yarn test error

### ISSUE THREAD

**Issue by 10142904** [geeksonsecurity/illuminatejs#1]
Hi,
        I run "yarn install && yarn test" and get some errors:

`yarn install v1.15.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.41s.
yarn run v1.15.2
$ jest
 FAIL  test/arrays.test.ts
  ● Test suite failed to run

    Cannot find module '../src/index' from 'test-utils.ts'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (test/test-utils.ts:5:15)

 FAIL  test/samples.test.ts
  ● Test suite failed to run

    Cannot find module '../src/index' from 'test-utils.ts'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (test/test-utils.ts:5:15)

 FAIL  test/strings.test.ts
  ● Test suite failed to run

    Cannot find module '../src/index' from 'test-utils.ts'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (test/test-utils.ts:5:15)

 FAIL  test/for-loops.test.ts
  ● Test suite failed to run

    Cannot find module '../src/index' from 'test-utils.ts'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (test/test-utils.ts:5:15)

`

**Comment by wizche** [comment]
Thanks for reporting @10142904, the last commit changed the filename for the plugin. 
Now its fixed!
