### ISSUE TITLE
execute error

### ISSUE THREAD

**Issue by qq6r** [geeksonsecurity/illuminatejs#2]
i follow readme and execute babel.js with the babel-cli node module,but get error at last step:
 ./node_modules/@babel/cli/bin/babel.js --plugins "./babel-plugin-deobfuscate" project.f6eb1.js
{ Error: Cannot find module './babel-plugin-deobfuscate' from '/mnt/d/illuminatejs'
    at Function.module.exports [as sync] (/mnt/d/illuminatejs/node_modules/resolve/lib/sync.js:58:15)
    at resolveStandardizedName (/mnt/d/illuminatejs/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
    at resolvePlugin (/mnt/d/illuminatejs/node_modules/@babel/core/lib/config/files/plugins.js:54:10)
    at loadPlugin (/mnt/d/illuminatejs/node_modules/@babel/core/lib/config/files/plugins.js:62:20)
    at createDescriptor (/mnt/d/illuminatejs/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at items.map (/mnt/d/illuminatejs/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/mnt/d/illuminatejs/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPluginDescriptors (/mnt/d/illuminatejs/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/mnt/d/illuminatejs/node_modules/@babel/core/lib/config/config-descriptors.js:63:49) code: 'MODULE_NOT_FOUND' }

The complete steps are as follows:
1 git clone https://github.com/geeksonsecurity/illuminatejs.git
2 cd illuminatejs/babel-plugin-deobfuscate directory,yarn install,yarn build
3 cd illuminatejs directory,npm install @babel/core @babel/cli
4 ./node_modules/@babel/cli/bin/babel.js --plugins "./babel-plugin-deobfuscate"  test.js
and the error occured at step 4
any mistake above?

**Comment by wizche** [comment]
Looks like you need to specify the full path to the plugin module. E.g.:
```
$ babel.js --plugins "./babel-plugin-deobfuscate/lib/illuminatejs.js" test.js
```

I will update the doc accordingly
