### ISSUE TITLE
SyntaxError: 'return' outside of function 

### ISSUE THREAD

**Issue by 10142904** [geeksonsecurity/illuminatejs#3]
Hi, 

         Thank you for fixing the test error, it is ok now. but when i deobfuscate a js, it report a error.

`[root@izbp1a5bxfhn22fz3yercfz illuminatejs]# ./node_modules/@babel/cli/bin/babel.js --plugins "./babel-plugin-deobfuscate/lib/illuminatejs.js"  apu.js 
Unknown loop control variable
Unknown loop control variable
Unknown loop control variable
Unknown loop control variable
{ SyntaxError: 'return' outside of function (1:27)
    at Parser.pp$5.raise (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp$1.parseReturnStatement (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:2066:10)
    at Parser.pp$1.parseStatement (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:1848:19)
    at Parser.pp$1.parseBlockBody (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$1.parseStatement (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:1868:19)
    at Parser.pp$1.parseIfStatement (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:2059:26)
    at Parser.pp$1.parseStatement (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:1846:19)
    at Parser.pp$1.parseBlockBody (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/root/illuminatejs/babel-plugin-deobfuscate/node_modules/babylon/lib/index.js:2247:8) pos: 27, loc: Position { line: 1, column: 27 } }

the `js's url is https://deloplen.com/apu.php?zoneid=2498696.

**Comment by wizche** [comment]
Any chance to get a minimal version of the JS causing the same error?

**Comment by 10142904** [comment]
there is a minmal version of the js which cause the same error
[a.js.txt](https://github.com/geeksonsecurity/illuminatejs/files/3175481/a.js.txt)

**Comment by 10142904** [comment]
I found a mimnaler version of the js:

function aa(i) {
        var str = "abcde";
        var a = 0;
        var f;
        var e;
        var Y = 0;
        for (; e = str.charAt(Y++); f = a%4?0:e)
        {
        }
}

deobfuscate it get error:

TypeError: Expected node path of type Expression
    at NodePath.(anonymous function) [as assertExpression] (/root/illuminatejs/node_modules/@babel/traverse/lib/path/index.js:206:13)
    at Object.evaluateExpression (/root/illuminatejs/babel-plugin-deobfuscate/lib/expressions.js:30:10)
    at evaluateInit (/root/illuminatejs/babel-plugin-deobfuscate/lib/identifiers.js:76:26)
    at evaluate (/root/illuminatejs/babel-plugin-deobfuscate/lib/identifiers.js:51:20)
    at evaluateExpression (/root/illuminatejs/babel-plugin-deobfuscate/lib/expressions.js:32:12)
    at evaluateConditionalExpression (/root/illuminatejs/babel-plugin-deobfuscate/lib/expressions.js:81:22)
    at evaluateExpression (/root/illuminatejs/babel-plugin-deobfuscate/lib/expressions.js:32:12)
    at PluginPass.deobfuscateExpression (/root/illuminatejs/babel-plugin-deobfuscate/lib/expressions.js:20:18)
    at PluginPass.newFn (/root/illuminatejs/node_modules/@babel/traverse/lib/visitors.js:230:17)
    at newFn (/root/illuminatejs/node_modules/@babel/traverse/lib/visitors.js:193:21)

**Comment by Pghgqx3h** [comment]
I broke it down to:
```javascript
var a;
a % 4;
```
